# Generated by Django 5.0.6 on 2024-08-28 09:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('time', models.CharField(choices=[('>6 months', 'More than 6 months'), ('3 - 6', '3 to 6 months'), ('1 - 3', '1 to 3 months')], max_length=50)),
                ('experience', models.CharField(choices=[('entry', 'Entry'), ('intermediate', 'Intermediate'), ('experienced', 'Experienced')], max_length=50)),
                ('budget', models.DecimalField(decimal_places=2, max_digits=12)),
                ('category', models.ManyToManyField(to='work.category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('freelancer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freelancer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
