# Generated by Django 5.0.6 on 2024-08-31 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0002_proposal'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='price',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
