# Generated by Django 5.0.6 on 2024-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('work', '0004_proposal_client_alter_proposal_freelancer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='description',
            field=models.CharField(max_length=6000),
        ),
    ]
